### ISSUE TITLE
Question: How do you get your data?

### ISSUE THREAD

**Issue by GeorgesOatesLarsen** [skribbliohints/skribbliohints.github.io#1]
Hi! How are you sourcing this list?

Thanks,

-- Georges

**Comment by dosu0** [comment]
He used a bot. To play games

**Comment by skribbliohints** [comment]
The data was collected by a bot that played skribblio for a few months in late 2019.  The bot played both public and private games.  [Some of the data is faulty.](https://github.com/skribbliohints/skribbliohints.github.io/issues/2#issuecomment-618664463)  Recently, the bot played in German just enough to get a complete list of words but not enough to get difficulty statistics.
