### ISSUE TITLE
Filter hint issue in Spanish

### ISSUE THREAD

**Issue by ghost** [skribbliohints/skribbliohints.github.io#4]
The filter doesn't work for some words, and it's because Spanish contains these letters: á - é - í - ó - ú - ñ.
for example if you put _ _ _ all the words that contains 3 letters will appear except those that contain the letters mentioned above such as: "río" "día" "tío". Maybe modifying the regex on getFilterFromSkribblioHint() and putting those letters will solve it.

**Comment by skribbliohints** [comment]
This issue is helpful.  I am pushing a commit that should fix this.
